[project]
name = "babamul-basic-streaming-example"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "astropy>=7.2.0",
    "babamul",
    "dotenv>=0.9.9",
    "jupyter>=1.1.1",
    "tqdm>=4.67.3",
]
